services:
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: conpresp

    volumes:
      - ./init:/docker-entrypoint-initdb.d
