spring:
  datasource:
    url: jdbc:mysql:5.7.34://localhost:3306/conpresp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update